spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: feed-service
  datasource:
    url: jdbc:postgresql://localhost:5432/decp_feed_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
