spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/decp_auth_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081

user-service:
  url: http://localhost:8082
